Repository ft-minigame/mini-backend, pull requests merged in 2023-05, with the labels that each got.

#11 build: initialize migration with typeORM
  package.json
  src/app.module.ts
  src/config/database.config.ts
  src/config/typeORM.config.ts
Labels: build

#13 fix: remove migrationRund at database
  src/config/database.config.ts
Labels: bug

#14 build: create user repository
  src/config/database.config.ts
  src/v1/users/domain/models/user.entity.ts
  src/v1/users/domain/repositories/users.repository.ts
Labels: build

#16 build: initialize rank
  src/app.module.ts
  src/v1/rank/controllers/rank.controller.ts
  src/v1/rank/domain/repositories/rank.repository.ts
  src/v1/rank/domain/services/rank.service.ts
  src/v1/rank/rank.module.ts
  src/v1/users/domain/models/user.entity.ts
Labels: build

#22 feat: create user dtos
  package-lock.json
  package.json
  src/main.ts
  src/v1/users/domain/models/user.entity.ts
  src/v1/users/dto/create-user.dto.ts
  src/v1/users/dto/update-user.dto.ts
Labels: enhancement
